baseURL: "https://equitable-policy-22.netlify.app/"
languageCode: en-us
title: LPPS 5360
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: 
enableEmoji: yes
publishDir: docs
params:
  description: Fall 2022
  author:
    name: "Professor: Michele Claibourn"
    description: "(Director of Equitable Analysis, UVA Equity Center)"
    thumbnail: /images/imagining.png
  index:
    alertbar: no
    mdtext: |
      
      *Dr. Michele Claibourn (Director of Equitable Analysis, UVA Equity Center and Assistant Professor in Batten)*
      
      **Email: mclaibourn@virginia.edu  |  Office Hours: TBD, or by appt.  |  Office: Let's meet outside or on zoom**
    picture: /images/imagining.png
    subtitle: Fall 2022, Tuesdays, 3:30-6:00
    title: LPPS 5360
  logo: /images/imagining_small.png
  social:
    github: mclaibourn
    twitter: mclaibourn
    linkedin: mclaibourn
    mail: mclaibourn@virginia.edu
menu:
  main:
    - identifier: syllabus
      name: Syllabus
      url: /static/syllabus
      weight: 100
    - identifier: schedule
      name: Schedule
      url: /static/schedule
      weight: 200
    - identifier: projects
      name: Projects
      url: /static/projects
      weight: 300
    - identifier: perusall
      name: Perusall
      url: https://perusall.com/
      weight: 400
    - identifier: collab
      name: Class Collab
      url: https://collab.its.virginia.edu/portal/site/e47df25c-4101-4391-ada9-3384695466da
      weight: 500
    - identifier: policy
      name: Batten Policies
      url: /static/policy
      weight: 600

markup:
  goldmark:
    renderer:
      unsafe: true
