---
title: "Assignments"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem Set 1

Due 10/19, by the start of class.

### R practice: playing with legos!
Download the [ps1.R](../ps/ps1.R) script and name it: lastname_ps1.R. Complete the tasks as described in the script and save. You'll submit the completed script to me on slack (via direct message). I should be able to run the script as is (line by line) with no errors.

### Find data
Identify a data source you'd like to use for the final visualization. I've provided [links to a variety of sources](../resources/) to help you out. The data can be anything that interests you! 

Part of each week's work will be using the chosen data set. To make our exchanges around this individual work easier, create a folder that contains the chosen data, an .Rproj file, and the weekly scripts you create using the data. You'll zip this up and share it with me so that I can follow/review your work.

For the first week, create a script that

1. Reads in the data
2. Examines the data using some of the functions in PS 1, Question 2
3. Via comments (#), notes the likely key variables of interest
4. Via comments, notes any initial issues you see with the data -- formats you'll need to fix, variables you'll need to derive, possible limitations. 

Your comments don't need to foreshadow everything; just start getting familiar with the data set and be thinking about some possible questions you might ask of it.